"""Reinitializing database

Revision ID: b3316788e7a1
Revises: 
Create Date: 2025-02-12 20:40:29.241745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3316788e7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add the username column with nullable=True initially
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])  # Explicit name added
        batch_op.drop_column('email')

    # Now, update the column to be NOT NULL (you should fill any NULL values before doing this)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint('uq_users_username', type_='unique')  # Drop by the constraint name
        batch_op.drop_column('username')

    # ### end Alembic commands ###
